// artisan/src/lib/i18n/locales/gu.ts — Gujarati
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(t: any, s: any): any { const r = { ...s }; for (const k in t) { if (typeof t[k] === 'object' && !Array.isArray(t[k])) { r[k] = deepMerge(t[k], s[k] || {}); } else { r[k] = t[k]; } } return r; }
const p = {
  common: { appName: 'કલાકૃતિ', loading: 'લોડ થઈ રહ્યું છે...', save: 'સાચવો', cancel: 'રદ કરો', delete: 'કાઢી નાખો', search: 'શોધો', viewAll: 'બધું જુઓ', addToCart: 'કાર્ટમાં ઉમેરો', addedToCart: 'કાર્ટમાં ઉમેરાયું!', outOfStock: 'સ્ટોકમાં નથી', featured: 'વિશેષ', products: 'ઉત્પાદનો' },
  nav: { home: 'હોમ', products: 'ઉત્પાદનો', explore: 'શોધખોળ', cart: 'કાર્ટ', login: 'લોગિન', signUp: 'સાઇન અપ', logIn: 'લોગ ઇન', logOut: 'લોગ આઉટ', logout: 'લોગઆઉટ', myAccount: 'મારું ખાતું', orders: 'ઓર્ડર', myOrders: 'મારા ઓર્ડર', wishlist: 'ઇચ્છા સૂચિ', sellerDashboard: 'વિક્રેતા ડેશબોર્ડ', adminDashboard: 'એડમિન ડેશબોર્ડ', accountSettings: 'ખાતા સેટિંગ્સ', signInPrompt: 'સાઇન ઇન કરો' },
  home: { heroTag: 'પ્રેમથી હસ્તનિર્મિત', heroTitle1: 'અનોખી શોધો', heroTitle2: 'ખજાના', heroSubtitle: 'સ્થાનિક કારીગરોને ટેકો આપો.', exploreProducts: 'ઉત્પાદનો જુઓ', becomeASeller: 'વિક્રેતા બનો', artisans: 'કારીગરો', happyBuyers: 'ખુશ ખરીદદારો', shopByCategory: 'શ્રેણી પ્રમાણે ખરીદો', browseCurated: 'અમારા સંગ્રહો જુઓ', handPicked: 'હાથથી ચૂંટેલા', featuredProducts: 'વિશેષ ઉત્પાદનો', noFeaturedProducts: 'હજુ કોઈ વિશેષ ઉત્પાદનો નથી', popular: 'લોકપ્રિય', trendingNow: 'ટ્રેન્ડિંગ', noTrendingProducts: 'હજુ કોઈ ટ્રેન્ડિંગ ઉત્પાદનો નથી', forArtisans: 'કારીગરો માટે', ctaTitle: 'તમારી કલાકૃતિ યાત્રા શરૂ કરો', ctaSubtitle: 'હજારો કારીગરો સાથે જોડાઓ.', ctaBenefit1: '5 મિનિટમાં સરળ સેટઅપ', ctaBenefit2: 'ઓછું કમિશન', ctaBenefit3: 'સમર્પિત સહાય', ctaBenefit4: 'વૈશ્વિક બજાર', openShop: 'આજે જ દુકાન ખોલો', activeSellers: 'સક્રિય વિક્રેતાઓ', happyCustomers: 'ખુશ ગ્રાહકો', totalSales: 'કુલ વેચાણ', averageRating: 'સરેરાશ રેટિંગ', featuredShops: 'વિશેષ દુકાનો', featuredShopsDesc: 'પ્રતિભાશાળી કારીગરો શોધો', verifiedSeller: 'ચકાસાયેલ', visitShop: 'દુકાન જુઓ', productsCount: '{count} ઉત્પાદનો', salesCount: '{count} વેચાણ', testimonials: 'અમારો સમુદાય શું કહે છે', testimonialsDesc: 'કલાકૃતિને પ્રેમ કરનારાઓની વાર્તાઓ', newsletterTitle: 'જોડાયેલા રહો', newsletterSubtitle: 'વિશેષ ઓફર મેળવો.', newsletterPlaceholder: 'તમારું ઈમેલ દાખલ કરો', newsletterButton: 'સબ્સ્ક્રાઇબ', newsletterSuccess: 'સફળતાપૂર્વક સબ્સ્ક્રાઇબ!', newsletterDisclaimer: 'અમારી ગોપનીયતા નીતિ સાથે સંમત.' },
  search: { placeholder: 'હસ્તકલા ઉત્પાદનો શોધો...', searching: 'શોધી રહ્યા છે...', noProducts: 'કોઈ ઉત્પાદનો મળ્યા નથી', viewAllResults: '"{query}" ના બધા પરિણામો' },
  footer: { description: 'અનોખા હસ્તકલા ઉત્પાદનો શોધો.', shop: 'ખરીદી', allProducts: 'બધા ઉત્પાદનો', featured: 'વિશેષ', newArrivals: 'નવા આગમન', bestSellers: 'બેસ્ટ સેલર્સ', support: 'સહાય', helpCenter: 'મદદ કેન્દ્ર', shippingInfo: 'શિપિંગ માહિતી', returns: 'પરત', contactUs: 'અમારો સંપર્ક કરો', sell: 'વેચાણ', becomeASeller: 'વિક્રેતા બનો', sellerDashboard: 'વિક્રેતા ડેશબોર્ડ', sellerGuide: 'વિક્રેતા માર્ગદર્શક', successStories: 'સફળતાની વાર્તાઓ', legal: 'કાનૂની', privacyPolicy: 'ગોપનીયતા નીતિ', termsOfService: 'સેવાની શરતો', cookiePolicy: 'કુકી નીતિ', refundPolicy: 'રિફંડ નીતિ', copyright: '© {year} કલાકૃતિ. સર્વ હક્ક અનામત.', madeWith: 'બનાવાયું', forArtisans: 'વિશ્વભરના કારીગરો માટે' },
};
const gu: TranslationKeys = deepMerge(p, en);
export default gu;
