// artisan/src/lib/i18n/locales/kn.ts — Kannada
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(t: any, s: any): any { const r = { ...s }; for (const k in t) { if (typeof t[k] === 'object' && !Array.isArray(t[k])) { r[k] = deepMerge(t[k], s[k] || {}); } else { r[k] = t[k]; } } return r; }
const p = {
  common: { appName: 'ಕಲಾಕೃತಿ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...', save: 'ಉಳಿಸಿ', cancel: 'ರದ್ದು', delete: 'ಅಳಿಸಿ', search: 'ಹುಡುಕಿ', viewAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ', addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ', addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ!', outOfStock: 'ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಇಲ್ಲ', featured: 'ವಿಶೇಷ', products: 'ಉತ್ಪನ್ನಗಳು' },
  nav: { home: 'ಹೋಮ್', products: 'ಉತ್ಪನ್ನಗಳು', explore: 'ಅನ್ವೇಷಿಸಿ', cart: 'ಕಾರ್ಟ್', login: 'ಲಾಗಿನ್', signUp: 'ಸೈನ್ ಅಪ್', logIn: 'ಲಾಗ್ ಇನ್', logOut: 'ಲಾಗ್ ಔಟ್', logout: 'ಲಾಗ್ಔಟ್', myAccount: 'ನನ್ನ ಖಾತೆ', orders: 'ಆರ್ಡರ್‌ಗಳು', myOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು', wishlist: 'ವಿಶ್‌ಲಿಸ್ಟ್', sellerDashboard: 'ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', adminDashboard: 'ನಿರ್ವಾಹಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', accountSettings: 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು', signInPrompt: 'ಸೈನ್ ಇನ್ ಮಾಡಿ' },
  home: { heroTag: 'ಉತ್ಸಾಹದಿಂದ ಕೈಯಲ್ಲಿ ಮಾಡಿದ', heroTitle1: 'ಅನನ್ಯ ಕಂಡುಹಿಡಿಯಿರಿ', heroTitle2: 'ನಿಧಿಗಳು', heroSubtitle: 'ಸ್ಥಳೀಯ ಕುಶಲಕರ್ಮಿಗಳಿಗೆ ಬೆಂಬಲ ನೀಡಿ.', exploreProducts: 'ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ', becomeASeller: 'ಮಾರಾಟಗಾರರಾಗಿ', artisans: 'ಕುಶಲಕರ್ಮಿಗಳು', happyBuyers: 'ಸಂತೋಷ ಖರೀದಿದಾರರು', shopByCategory: 'ವರ್ಗದ ಪ್ರಕಾರ ಖರೀದಿಸಿ', browseCurated: 'ನಮ್ಮ ಸಂಗ್ರಹಗಳನ್ನು ನೋಡಿ', handPicked: 'ಕೈಯಿಂದ ಆಯ್ಕೆ', featuredProducts: 'ವಿಶೇಷ ಉತ್ಪನ್ನಗಳು', noFeaturedProducts: 'ಇನ್ನೂ ವಿಶೇಷ ಉತ್ಪನ್ನಗಳಿಲ್ಲ', popular: 'ಜನಪ್ರಿಯ', trendingNow: 'ಟ್ರೆಂಡಿಂಗ್', noTrendingProducts: 'ಇನ್ನೂ ಟ್ರೆಂಡಿಂಗ್ ಉತ್ಪನ್ನಗಳಿಲ್ಲ', forArtisans: 'ಕುಶಲಕರ್ಮಿಗಳಿಗಾಗಿ', ctaTitle: 'ನಿಮ್ಮ ಕಲಾಕೃತಿ ಪ್ರಯಾಣ ಪ್ರಾರಂಭಿಸಿ', ctaSubtitle: 'ಸಾವಿರಾರು ಕುಶಲಕರ್ಮಿಗಳೊಂದಿಗೆ ಸೇರಿ.', ctaBenefit1: '5 ನಿಮಿಷದಲ್ಲಿ ಸುಲಭ ಸೆಟಪ್', ctaBenefit2: 'ಕಡಿಮೆ ಕಮಿಷನ್', ctaBenefit3: 'ಸಮರ್ಪಿತ ಬೆಂಬಲ', ctaBenefit4: 'ಜಾಗತಿಕ ಮಾರುಕಟ್ಟೆ', openShop: 'ಇಂದೇ ಅಂಗಡಿ ತೆರೆಯಿರಿ', activeSellers: 'ಸಕ್ರಿಯ ಮಾರಾಟಗಾರರು', happyCustomers: 'ಸಂತೋಷ ಗ್ರಾಹಕರು', totalSales: 'ಒಟ್ಟು ಮಾರಾಟ', averageRating: 'ಸರಾಸರಿ ರೇಟಿಂಗ್', featuredShops: 'ವಿಶೇಷ ಅಂಗಡಿಗಳು', featuredShopsDesc: 'ಪ್ರತಿಭಾವಂತ ಕುಶಲಕರ್ಮಿಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ', verifiedSeller: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', visitShop: 'ಅಂಗಡಿ ನೋಡಿ', productsCount: '{count} ಉತ್ಪನ್ನಗಳು', salesCount: '{count} ಮಾರಾಟ', testimonials: 'ನಮ್ಮ ಸಮುದಾಯ ಏನು ಹೇಳುತ್ತದೆ', testimonialsDesc: 'ಕಲಾಕೃತಿಯನ್ನು ಪ್ರೀತಿಸುವವರ ಕಥೆಗಳು', newsletterTitle: 'ಸಂಪರ್ಕದಲ್ಲಿರಿ', newsletterSubtitle: 'ವಿಶೇಷ ಆಫರ್‌ಗಳನ್ನು ಪಡೆಯಿರಿ.', newsletterPlaceholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ನಮೂದಿಸಿ', newsletterButton: 'ಚಂದಾದಾರರಾಗಿ', newsletterSuccess: 'ಯಶಸ್ವಿಯಾಗಿ ಚಂದಾದಾರರಾಗಿದ್ದೀರಿ!', newsletterDisclaimer: 'ನಮ್ಮ ಗೌಪ್ಯತೆ ನೀತಿಗೆ ಒಪ್ಪಿಗೆ.' },
  search: { placeholder: 'ಕೈಕೆಲಸ ಉತ್ಪನ್ನಗಳನ್ನು ಹುಡುಕಿ...', searching: 'ಹುಡುಕುತ್ತಿದೆ...', noProducts: 'ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ', viewAllResults: '"{query}" ನ ಎಲ್ಲಾ ಫಲಿತಾಂಶಗಳು' },
  footer: { description: 'ಅನನ್ಯ ಕೈಕೆಲಸ ಉತ್ಪನ್ನಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ.', shop: 'ಖರೀದಿ', allProducts: 'ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು', featured: 'ವಿಶೇಷ', newArrivals: 'ಹೊಸ ಆಗಮನ', bestSellers: 'ಅತ್ಯಧಿಕ ಮಾರಾಟ', support: 'ಬೆಂಬಲ', helpCenter: 'ಸಹಾಯ ಕೇಂದ್ರ', shippingInfo: 'ಶಿಪ್ಪಿಂಗ್ ಮಾಹಿತಿ', returns: 'ಹಿಂತಿರುಗಿಸಿ', contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ', sell: 'ಮಾರಾಟ', becomeASeller: 'ಮಾರಾಟಗಾರರಾಗಿ', sellerDashboard: 'ಮಾರಾಟಗಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', sellerGuide: 'ಮಾರಾಟಗಾರ ಮಾರ್ಗದರ್ಶಿ', successStories: 'ಯಶೋಗಾಥೆಗಳು', legal: 'ಕಾನೂನು', privacyPolicy: 'ಗೌಪ್ಯತೆ ನೀತಿ', termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು', cookiePolicy: 'ಕುಕೀ ನೀತಿ', refundPolicy: 'ಮರುಪಾವತಿ ನೀತಿ', copyright: '© {year} ಕಲಾಕೃತಿ. ಎಲ್ಲಾ ಹಕ್ಕುಗಳು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.', madeWith: 'ತಯಾರಿಸಲಾಗಿದೆ', forArtisans: 'ವಿಶ್ವಾದ್ಯಂತ ಕುಶಲಕರ್ಮಿಗಳಿಗಾಗಿ' },
};
const kn: TranslationKeys = deepMerge(p, en);
export default kn;
