// artisan/src/lib/i18n/locales/ml.ts — Malayalam
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(t: any, s: any): any { const r = { ...s }; for (const k in t) { if (typeof t[k] === 'object' && !Array.isArray(t[k])) { r[k] = deepMerge(t[k], s[k] || {}); } else { r[k] = t[k]; } } return r; }
const p = {
  common: { appName: 'കലാകൃതി', loading: 'ലോഡ് ചെയ്യുന്നു...', save: 'സംരക്ഷിക്കുക', cancel: 'റദ്ദാക്കുക', delete: 'ഇല്ലാതാക്കുക', search: 'തിരയുക', viewAll: 'എല്ലാം കാണുക', addToCart: 'കാർട്ടിലേക്ക് ചേർക്കുക', addedToCart: 'കാർട്ടിലേക്ക് ചേർത്തു!', outOfStock: 'സ്റ്റോക്കില്ല', featured: 'പ്രത്യേക', products: 'ഉൽപ്പന്നങ്ങൾ' },
  nav: { home: 'ഹോം', products: 'ഉൽപ്പന്നങ്ങൾ', explore: 'പര്യവേക്ഷണം', cart: 'കാർട്ട്', login: 'ലോഗിൻ', signUp: 'സൈൻ അപ്പ്', logIn: 'ലോഗ് ഇൻ', logOut: 'ലോഗ് ഔട്ട്', logout: 'ലോഗ്ഔട്ട്', myAccount: 'എന്റെ അക്കൗണ്ട്', orders: 'ഓർഡറുകൾ', myOrders: 'എന്റെ ഓർഡറുകൾ', wishlist: 'വിഷ്‌ലിസ്റ്റ്', sellerDashboard: 'വിൽപ്പനക്കാരന്റെ ഡാഷ്‌ബോർഡ്', adminDashboard: 'അഡ്‌മിൻ ഡാഷ്‌ബോർഡ്', accountSettings: 'അക്കൗണ്ട് ക്രമീകരണങ്ങൾ', signInPrompt: 'സൈൻ ഇൻ ചെയ്യുക' },
  home: { heroTag: 'വികാരത്തോടെ കൈകൊണ്ട് നിർമ്മിച്ചത്', heroTitle1: 'അതുല്യം കണ്ടെത്തുക', heroTitle2: 'നിധികൾ', heroSubtitle: 'പ്രാദേശിക കരകൗശല വിദഗ്ധരെ പിന്തുണയ്ക്കുക.', exploreProducts: 'ഉൽപ്പന്നങ്ങൾ കാണുക', becomeASeller: 'വിൽപ്പനക്കാരൻ ആകുക', artisans: 'കരകൗശല വിദഗ്ധർ', happyBuyers: 'സന്തുഷ്ട വാങ്ങുന്നവർ', shopByCategory: 'വിഭാഗം അനുസരിച്ച്', browseCurated: 'ഞങ്ങളുടെ ശേഖരങ്ങൾ', handPicked: 'കൈകൊണ്ട് തിരഞ്ഞെടുത്ത', featuredProducts: 'പ്രത്യേക ഉൽപ്പന്നങ്ങൾ', noFeaturedProducts: 'പ്രത്യേക ഉൽപ്പന്നങ്ങൾ ഇല്ല', popular: 'ജനപ്രിയം', trendingNow: 'ട്രെൻഡിംഗ്', noTrendingProducts: 'ട്രെൻഡിംഗ് ഉൽപ്പന്നങ്ങൾ ഇല്ല', forArtisans: 'കരകൗശല വിദഗ്ധർക്ക്', ctaTitle: 'നിങ്ങളുടെ കലാകൃതി യാത്ര ആരംഭിക്കുക', ctaSubtitle: 'ആയിരക്കണക്കിന് കരകൗശല വിദഗ്ധരോടൊപ്പം ചേരുക.', ctaBenefit1: '5 മിനിറ്റിൽ എളുപ്പ സെറ്റപ്പ്', ctaBenefit2: 'കുറഞ്ഞ കമ്മീഷൻ', ctaBenefit3: 'സമർപ്പിത പിന്തുണ', ctaBenefit4: 'ആഗോള വിപണി', openShop: 'ഇന്ന് തന്നെ കട തുറക്കൂ', activeSellers: 'സജീവ വിൽപ്പനക്കാർ', happyCustomers: 'സന്തുഷ്ട ഉപഭോക്താക്കൾ', totalSales: 'ആകെ വിൽപ്പന', averageRating: 'ശരാശരി റേറ്റിംഗ്', featuredShops: 'പ്രത്യേക കടകൾ', featuredShopsDesc: 'പ്രതിഭാശാലികളെ കണ്ടെത്തുക', verifiedSeller: 'പരിശോധിച്ചു', visitShop: 'കട കാണുക', productsCount: '{count} ഉൽപ്പന്നങ്ങൾ', salesCount: '{count} വിൽപ്പന', testimonials: 'ഞങ്ങളുടെ സമൂഹം എന്ത് പറയുന്നു', testimonialsDesc: 'കലാകൃതിയെ ഇഷ്ടപ്പെടുന്നവരുടെ കഥകൾ', newsletterTitle: 'ബന്ധപ്പെട്ടിരിക്കുക', newsletterSubtitle: 'പ്രത്യേക ഓഫറുകൾ നേടുക.', newsletterPlaceholder: 'നിങ്ങളുടെ ഇമെയിൽ നൽകുക', newsletterButton: 'സബ്‌സ്‌ക്രൈബ്', newsletterSuccess: 'വിജയകരമായി സബ്‌സ്‌ക്രൈബ്!', newsletterDisclaimer: 'ഞങ്ങളുടെ സ്വകാര്യതാ നയത്തോട് യോജിക്കുന്നു.' },
  search: { placeholder: 'കരകൗശല ഉൽപ്പന്നങ്ങൾ തിരയുക...', searching: 'തിരയുന്നു...', noProducts: 'ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തിയില്ല', viewAllResults: '"{query}" ന്റെ എല്ലാ ഫലങ്ങളും' },
  footer: { description: 'അതുല്യ കരകൗശല ഉൽപ്പന്നങ്ങൾ കണ്ടെത്തുക.', shop: 'ഷോപ്പ്', allProducts: 'എല്ലാ ഉൽപ്പന്നങ്ങളും', featured: 'പ്രത്യേക', newArrivals: 'പുതിയ വരവുകൾ', bestSellers: 'ബെസ്റ്റ് സെല്ലേഴ്‌സ്', support: 'പിന്തുണ', helpCenter: 'സഹായ കേന്ദ്രം', shippingInfo: 'ഷിപ്പിംഗ് വിവരങ്ങൾ', returns: 'മടക്കിനൽകൽ', contactUs: 'ഞങ്ങളെ ബന്ധപ്പെടുക', sell: 'വിൽപ്പന', becomeASeller: 'വിൽപ്പനക്കാരൻ ആകുക', sellerDashboard: 'വിൽപ്പനക്കാരന്റെ ഡാഷ്‌ബോർഡ്', sellerGuide: 'വിൽപ്പനക്കാരൻ ഗൈഡ്', successStories: 'വിജയ കഥകൾ', legal: 'നിയമപരമായ', privacyPolicy: 'സ്വകാര്യതാ നയം', termsOfService: 'സേവന നിബന്ധനകൾ', cookiePolicy: 'കുക്കീ നയം', refundPolicy: 'റീഫണ്ട് നയം', copyright: '© {year} കലാകൃതി. എല്ലാ അവകാശങ്ങളും സംവരണം ചെയ്തിരിക്കുന്നു.', madeWith: 'നിർമ്മിച്ചത്', forArtisans: 'ലോകമെമ്പാടുമുള്ള കരകൗശല വിദഗ്ധർക്കായി' },
};
const ml: TranslationKeys = deepMerge(p, en);
export default ml;
