// artisan/src/lib/i18n/locales/mr.ts — Marathi
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(t: any, s: any): any { const r = { ...s }; for (const k in t) { if (typeof t[k] === 'object' && !Array.isArray(t[k])) { r[k] = deepMerge(t[k], s[k] || {}); } else { r[k] = t[k]; } } return r; }
const p = {
  common: { appName: 'कलाकृती', loading: 'लोड होत आहे...', save: 'जतन करा', cancel: 'रद्द करा', delete: 'हटवा', search: 'शोधा', viewAll: 'सर्व पहा', addToCart: 'कार्टमध्ये जोडा', addedToCart: 'कार्टमध्ये जोडले!', outOfStock: 'स्टॉकमध्ये नाही', featured: 'विशेष', products: 'उत्पादने' },
  nav: { home: 'मुख्यपृष्ठ', products: 'उत्पादने', explore: 'शोधा', cart: 'कार्ट', login: 'लॉगिन', signUp: 'साइन अप', logIn: 'लॉग इन', logOut: 'लॉग आउट', logout: 'लॉगआउट', myAccount: 'माझे खाते', orders: 'ऑर्डर', myOrders: 'माझे ऑर्डर', wishlist: 'इच्छा सूची', sellerDashboard: 'विक्रेता डॅशबोर्ड', adminDashboard: 'प्रशासक डॅशबोर्ड', accountSettings: 'खाते सेटिंग्ज', signInPrompt: 'साइन इन करा' },
  home: { heroTag: 'आवडीने हस्तनिर्मित', heroTitle1: 'अनोखे शोधा', heroTitle2: 'खजिने', heroSubtitle: 'स्थानिक कारागिरांना पाठिंबा द्या.', exploreProducts: 'उत्पादने पहा', becomeASeller: 'विक्रेता व्हा', artisans: 'कारागीर', happyBuyers: 'आनंदी खरेदीदार', shopByCategory: 'वर्गानुसार खरेदी', browseCurated: 'आमचे संग्रह पहा', handPicked: 'हाताने निवडलेले', featuredProducts: 'विशेष उत्पादने', noFeaturedProducts: 'अद्याप विशेष उत्पादने नाहीत', popular: 'लोकप्रिय', trendingNow: 'ट्रेंडिंग', noTrendingProducts: 'अद्याप ट्रेंडिंग उत्पादने नाहीत', forArtisans: 'कारागिरांसाठी', ctaTitle: 'तुमचा कलाकृती प्रवास सुरू करा', ctaSubtitle: 'हजारो कारागिरांसोबत सामील व्हा.', ctaBenefit1: '५ मिनिटांत सोपी सेटअप', ctaBenefit2: 'कमी कमिशन', ctaBenefit3: 'समर्पित सहाय्य', ctaBenefit4: 'जागतिक बाजारपेठ', openShop: 'आजच दुकान उघडा', activeSellers: 'सक्रिय विक्रेते', happyCustomers: 'आनंदी ग्राहक', totalSales: 'एकूण विक्री', averageRating: 'सरासरी रेटिंग', featuredShops: 'विशेष दुकाने', featuredShopsDesc: 'प्रतिभावान कारागीर शोधा', verifiedSeller: 'सत्यापित', visitShop: 'दुकान पहा', productsCount: '{count} उत्पादने', salesCount: '{count} विक्री', testimonials: 'आमचा समुदाय काय म्हणतो', testimonialsDesc: 'कलाकृती आवडणाऱ्यांच्या कथा', newsletterTitle: 'जोडलेले रहा', newsletterSubtitle: 'विशेष ऑफर मिळवा.', newsletterPlaceholder: 'तुमचा ईमेल प्रविष्ट करा', newsletterButton: 'सबस्क्राइब', newsletterSuccess: 'यशस्वीरित्या सबस्क्राइब!', newsletterDisclaimer: 'आमच्या गोपनीयता धोरणाशी सहमत.' },
  search: { placeholder: 'हस्तकला उत्पादने शोधा...', searching: 'शोधत आहे...', noProducts: 'उत्पादने सापडली नाहीत', viewAllResults: '"{query}" चे सर्व निकाल' },
  footer: { description: 'अनोखी हस्तकला उत्पादने शोधा.', shop: 'खरेदी', allProducts: 'सर्व उत्पादने', featured: 'विशेष', newArrivals: 'नवीन आगमन', bestSellers: 'सर्वाधिक विकले जाणारे', support: 'सहाय्य', helpCenter: 'मदत केंद्र', shippingInfo: 'शिपिंग माहिती', returns: 'परतावा', contactUs: 'संपर्क करा', sell: 'विक्री', becomeASeller: 'विक्रेता व्हा', sellerDashboard: 'विक्रेता डॅशबोर्ड', sellerGuide: 'विक्रेता मार्गदर्शक', successStories: 'यशोगाथा', legal: 'कायदेशीर', privacyPolicy: 'गोपनीयता धोरण', termsOfService: 'सेवा अटी', cookiePolicy: 'कुकी धोरण', refundPolicy: 'परतावा धोरण', copyright: '© {year} कलाकृती. सर्व हक्क राखीव.', madeWith: 'बनवले', forArtisans: 'जगभरातील कारागिरांसाठी' },
};
const mr: TranslationKeys = deepMerge(p, en);
export default mr;
