// artisan/src/lib/i18n/locales/ta.ts — Tamil
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(target: any, source: any): any { const result = { ...source }; for (const key in target) { if (typeof target[key] === 'object' && !Array.isArray(target[key])) { result[key] = deepMerge(target[key], source[key] || {}); } else { result[key] = target[key]; } } return result; }

const taPartial = {
  common: { appName: 'கலாகிருதி', loading: 'ஏற்றுகிறது...', save: 'சேமி', cancel: 'ரத்து', delete: 'நீக்கு', edit: 'திருத்து', update: 'புதுப்பி', search: 'தேடு', viewAll: 'அனைத்தையும் காண', noResults: 'முடிவுகள் இல்லை', addToCart: 'கார்ட்டில் சேர்', addedToCart: 'கார்ட்டில் சேர்க்கப்பட்டது!', outOfStock: 'இருப்பில் இல்லை', featured: 'சிறப்பு', products: 'பொருட்கள்' },
  nav: { home: 'முகப்பு', products: 'பொருட்கள்', explore: 'ஆராயுங்கள்', cart: 'கார்ட்', login: 'உள்நுழை', signUp: 'பதிவு', logIn: 'உள்நுழை', logOut: 'வெளியேறு', logout: 'வெளியேறு', myAccount: 'என் கணக்கு', orders: 'ஆர்டர்கள்', myOrders: 'என் ஆர்டர்கள்', wishlist: 'விருப்பப்பட்டியல்', sellerDashboard: 'விற்பனையாளர் டாஷ்போர்டு', adminDashboard: 'நிர்வாக டாஷ்போர்டு', accountSettings: 'கணக்கு அமைப்புகள்', signInPrompt: 'உள்நுழையவும்' },
  home: { heroTag: 'ஆர்வத்துடன் கைவினை', heroTitle1: 'தனித்துவமான கண்டுபிடி', heroTitle2: 'கருவூலங்கள்', heroSubtitle: 'உள்ளூர் கைவினைஞர்களை ஆதரிக்கவும்.', exploreProducts: 'பொருட்களை ஆராயுங்கள்', becomeASeller: 'விற்பனையாளராகுங்கள்', artisans: 'கைவினைஞர்கள்', happyBuyers: 'மகிழ்ச்சியான வாங்குபவர்கள்', shopByCategory: 'வகை வாரியாக வாங்கு', browseCurated: 'எங்கள் தொகுப்புகளை உலாவுங்கள்', handPicked: 'கையால் தேர்ந்தெடுக்கப்பட்ட', featuredProducts: 'சிறப்பு பொருட்கள்', noFeaturedProducts: 'சிறப்பு பொருட்கள் இல்லை', popular: 'பிரபலம்', trendingNow: 'டிரெண்டிங்', noTrendingProducts: 'டிரெண்டிங் பொருட்கள் இல்லை', forArtisans: 'கைவினைஞர்களுக்கு', ctaTitle: 'உங்கள் கலாகிருதி பயணத்தை தொடங்குங்கள்', ctaSubtitle: 'ஆயிரக்கணக்கான கைவினைஞர்களுடன் சேருங்கள்.', ctaBenefit1: '5 நிமிடத்தில் எளிய அமைப்பு', ctaBenefit2: 'குறைந்த கமிஷன்', ctaBenefit3: 'அர்ப்பணிப்பான ஆதரவு', ctaBenefit4: 'உலகளாவிய சந்தை', openShop: 'இன்றே கடை திறக்கவும்', activeSellers: 'செயலில் உள்ள விற்பனையாளர்கள்', happyCustomers: 'மகிழ்ச்சியான வாடிக்கையாளர்கள்', totalSales: 'மொத்த விற்பனை', averageRating: 'சராசரி மதிப்பீடு', featuredShops: 'சிறப்பு கடைகள்', featuredShopsDesc: 'திறமையான கைவினைஞர்களை கண்டறியுங்கள்', verifiedSeller: 'சரிபார்க்கப்பட்டது', visitShop: 'கடையை பாருங்கள்', productsCount: '{count} பொருட்கள்', salesCount: '{count} விற்பனை', testimonials: 'எங்கள் சமூகம் என்ன சொல்கிறது', testimonialsDesc: 'கலாகிருதியை விரும்புவோரின் கதைகள்', newsletterTitle: 'தொடர்பில் இருங்கள்', newsletterSubtitle: 'புதிய வரவுகள் மற்றும் சிறப்பு சலுகைகளை பெறுங்கள்.', newsletterPlaceholder: 'உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்', newsletterButton: 'குழுசேர்', newsletterSuccess: 'வெற்றிகரமாக குழுசேர்ந்தது!', newsletterDisclaimer: 'குழுசேர்வதன் மூலம் எங்கள் தனியுரிமைக் கொள்கையை ஏற்கிறீர்கள்.' },
  search: { placeholder: 'கைவினை பொருட்களை தேடுங்கள்...', searching: 'தேடுகிறது...', noProducts: 'பொருட்கள் இல்லை', viewAllResults: '"{query}" க்கான அனைத்து முடிவுகள்' },
  footer: { description: 'தனித்துவமான கைவினை பொருட்களை கண்டறியுங்கள்.', shop: 'கடை', allProducts: 'அனைத்து பொருட்கள்', featured: 'சிறப்பு', newArrivals: 'புதிய வரவுகள்', bestSellers: 'அதிகம் விற்பவை', support: 'ஆதரவு', helpCenter: 'உதவி மையம்', shippingInfo: 'அனுப்புதல் தகவல்', returns: 'திரும்ப', contactUs: 'எங்களை தொடர்பு கொள்ளுங்கள்', sell: 'விற்பனை', becomeASeller: 'விற்பனையாளராகுங்கள்', sellerDashboard: 'விற்பனையாளர் டாஷ்போர்டு', sellerGuide: 'விற்பனையாளர் வழிகாட்டி', successStories: 'வெற்றிக் கதைகள்', legal: 'சட்ட', privacyPolicy: 'தனியுரிமைக் கொள்கை', termsOfService: 'சேவை விதிமுறைகள்', cookiePolicy: 'குக்கீ கொள்கை', refundPolicy: 'பணத்திரும்ப கொள்கை', copyright: '© {year} கலாகிருதி. அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.', madeWith: 'உருவாக்கப்பட்டது', forArtisans: 'உலகளாவிய கைவினைஞர்களுக்காக' },
};

const ta: TranslationKeys = deepMerge(taPartial, en);
export default ta;
