// artisan/src/lib/i18n/locales/te.ts — Telugu
import type { TranslationKeys } from './en';
import en from './en';
function deepMerge(t: any, s: any): any { const r = { ...s }; for (const k in t) { if (typeof t[k] === 'object' && !Array.isArray(t[k])) { r[k] = deepMerge(t[k], s[k] || {}); } else { r[k] = t[k]; } } return r; }
const p = {
  common: { appName: 'కళాకృతి', loading: 'లోడ్ అవుతోంది...', save: 'సేవ్', cancel: 'రద్దు', delete: 'తొలగించు', search: 'వెతుకు', viewAll: 'అన్నీ చూడండి', addToCart: 'కార్ట్‌కు జోడించు', addedToCart: 'కార్ట్‌కు జోడించబడింది!', outOfStock: 'స్టాక్‌లో లేదు', featured: 'ప్రత్యేక', products: 'ఉత్పత్తులు' },
  nav: { home: 'హోమ్', products: 'ఉత్పత్తులు', explore: 'అన్వేషించండి', cart: 'కార్ట్', login: 'లాగిన్', signUp: 'సైన్ అప్', logIn: 'లాగ్ ఇన్', logOut: 'లాగ్ అవుట్', logout: 'లాగ్అవుట్', myAccount: 'నా ఖాతా', orders: 'ఆర్డర్లు', myOrders: 'నా ఆర్డర్లు', wishlist: 'విష్‌లిస్ట్', sellerDashboard: 'విక్రేత డాష్‌బోర్డ్', adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్', accountSettings: 'ఖాతా సెట్టింగ్‌లు', signInPrompt: 'సైన్ ఇన్ చేయండి' },
  home: { heroTag: 'ఆవేశంతో చేతిపని', heroTitle1: 'అద్భుతమైన కనుగొనండి', heroTitle2: 'నిధులు', heroSubtitle: 'స్థానిక కళాకారులకు మద్దతు ఇవ్వండి.', exploreProducts: 'ఉత్పత్తులు చూడండి', becomeASeller: 'విక్రేత అవ్వండి', artisans: 'కళాకారులు', happyBuyers: 'సంతోష కొనుగోలుదారులు', shopByCategory: 'వర్గం ప్రకారం', browseCurated: 'మా సేకరణలు చూడండి', handPicked: 'చేతితో ఎంపిక', featuredProducts: 'ప్రత్యేక ఉత్పత్తులు', noFeaturedProducts: 'ప్రత్యేక ఉత్పత్తులు లేవు', popular: 'ప్రజాదరణ', trendingNow: 'ట్రెండింగ్', noTrendingProducts: 'ట్రెండింగ్ ఉత్పత్తులు లేవు', forArtisans: 'కళాకారుల కోసం', ctaTitle: 'మీ కళాకృతి ప్రయాణం ప్రారంభించండి', ctaSubtitle: 'వేలాది కళాకారులతో చేరండి.', ctaBenefit1: '5 నిమిషాల్లో సెటప్', ctaBenefit2: 'తక్కువ కమీషన్', ctaBenefit3: 'అంకితమైన మద్దతు', ctaBenefit4: 'ప్రపంచ మార్కెట్', openShop: 'ఈరోజే షాప్ తెరవండి', activeSellers: 'క్రియాశీల విక్రేతలు', happyCustomers: 'సంతోష కస్టమర్లు', totalSales: 'మొత్తం అమ్మకాలు', averageRating: 'సగటు రేటింగ్', featuredShops: 'ప్రత్యేక షాపులు', featuredShopsDesc: 'ప్రతిభావంతులను కనుగొనండి', verifiedSeller: 'ధృవీకరించబడింది', visitShop: 'షాప్ చూడండి', productsCount: '{count} ఉత్పత్తులు', salesCount: '{count} అమ్మకాలు', testimonials: 'మా సమూహం ఏమంటుంది', testimonialsDesc: 'కళాకృతిని ఇష్టపడేవారి కథలు', newsletterTitle: 'అనుసంధానంలో ఉండండి', newsletterSubtitle: 'ప్రత్యేక ఆఫర్లు పొందండి.', newsletterPlaceholder: 'ఈమెయిల్ చిరునామా', newsletterButton: 'సబ్‌స్క్రైబ్', newsletterSuccess: 'విజయవంతంగా సబ్‌స్క్రైబ్!', newsletterDisclaimer: 'మా గోప్యతా విధానానికి అంగీకరిస్తారు.' },
  search: { placeholder: 'చేతిపని ఉత్పత్తులు వెతకండి...', searching: 'వెతుకుతోంది...', noProducts: 'ఉత్పత్తులు కనబడలేదు', viewAllResults: '"{query}" అన్ని ఫలితాలు' },
  footer: { description: 'అద్భుతమైన చేతిపని ఉత్పత్తులను కనుగొనండి.', shop: 'షాపింగ్', allProducts: 'అన్ని ఉత్పత్తులు', featured: 'ప్రత్యేక', newArrivals: 'కొత్త రాకలు', bestSellers: 'బెస్ట్ సెల్లర్స్', support: 'మద్దతు', helpCenter: 'సహాయ కేంద్రం', shippingInfo: 'షిప్పింగ్ సమాచారం', returns: 'రిటర్న్స్', contactUs: 'మమ్మల్ని సంప్రదించండి', sell: 'అమ్మకం', becomeASeller: 'విక్రేత అవ్వండి', sellerDashboard: 'విక్రేత డాష్‌బోర్డ్', sellerGuide: 'విక్రేత గైడ్', successStories: 'విజయ గాథలు', legal: 'చట్టపరమైన', privacyPolicy: 'గోప్యతా విధానం', termsOfService: 'సేవా నిబంధనలు', cookiePolicy: 'కుకీ విధానం', refundPolicy: 'రిఫండ్ విధానం', copyright: '© {year} కళాకృతి. అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.', madeWith: 'తయారు చేయబడింది', forArtisans: 'ప్రపంచవ్యాప్త కళాకారుల కోసం' },
};
const te: TranslationKeys = deepMerge(p, en);
export default te;
